In [3]:
import numpy as np

In [2]:
# Array Operations

In [3]:
# Arithmetic Operations

In [4]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [5]:
a1

array([1, 2, 3, 4, 5])

In [6]:
a2

array([ 6,  7,  8,  9, 10])

In [7]:
add = a1 + a2
add

array([ 7,  9, 11, 13, 15])

In [8]:
mult = a1 * a2
mult

array([ 6, 14, 24, 36, 50])

In [9]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1 // a2

array([0, 0, 0, 0, 0])

In [12]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [13]:
# Broadcasting

In [14]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [16]:
broadCast = arr + 10
broadCast

array([20, 30, 40, 50])

In [6]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
arr = arr + 10

In [9]:
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [11]:
arr = arr * 2
arr

array([[ 44,  48,  52,  56,  60],
       [ 64,  68,  72,  76,  80],
       [ 84,  88,  92,  96, 100],
       [104, 108, 112, 116, 120],
       [124, 128, 132, 136, 140]])

In [13]:
a = np.arange(1,26)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [16]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [18]:
a[4:6] * 10
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [20]:
b = a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [21]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [22]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
# Deep and Shallow Copy

In [24]:
arr1 = np.arange(1,26)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [26]:
b = arr1.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [27]:
b[0] = 101
b

array([101,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25])

In [28]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [29]:
# Matrix Operations

In [30]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [31]:
A

array([[1, 2],
       [3, 4]])

In [32]:
B

array([[5, 6],
       [7, 8]])

In [33]:
A * B

array([[ 5, 12],
       [21, 32]])

In [34]:
A @ B

array([[19, 22],
       [43, 50]])

In [35]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [36]:
A.T #Transpose

array([[1, 3],
       [2, 4]])

In [37]:
# Advance Array Manipulation

In [ ]:
# Stacking Array

In [38]:
A

array([[1, 2],
       [3, 4]])

In [39]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
# Cannot mtarix arrays, only able to do with list arrays or vectors

In [40]:
# create separate arrays:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [41]:
arr1 = np.vstack((a,b))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
arr2 = np.hstack((a,b))
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
col = np.column_stack((a,b))
col

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
# Splitting Arrays, Only happened with equal divisions

In [45]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
split = np.hsplit(c, 2)
split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(c, 3) # Will get error

In [49]:
np.hsplit(c, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [50]:
np.vsplit(c, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [51]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [52]:
arr = np.vsplit(c,4)

In [53]:
for i in arr:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
