In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [11]:
a = [1,2,3.5,4,5,5, "Hello"]


In [12]:
a

[1, 2, 3.5, 4, 5, 5, 'Hello']

In [13]:
np.array(a)

array(['1', '2', '3.5', '4', '5', '5', 'Hello'], dtype='<U32')

In [15]:
l = [[1,2,3], [4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [26]:
arr = np.zeros((4,8)) # Rows and columns
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [33]:
#Random Numbers

In [36]:
np.random.rand(10)

array([0.88775691, 0.62714599, 0.51061886, 0.03605749, 0.4211542 ,
       0.281179  , 0.14003441, 0.81719147, 0.72480688, 0.51917052])

In [37]:
np.random.randn(10)

array([-1.09745247,  1.06817887, -0.68843557,  1.20715702, -0.87160521,
       -0.29995171, -0.29356801,  0.12645484, -0.35561646,  1.75505665])

In [38]:
np.random.randint(6)

5

In [41]:
np.random.randint(10,20,10)

array([15, 18, 15, 14, 10, 18, 19, 12, 17, 18], dtype=int32)

In [42]:
# Array attributes


In [44]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr.shape

(3, 3)

In [46]:
arr.size

9

In [47]:
arr.dtype

dtype('int64')

In [48]:
# Array Methods

In [50]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.min()

np.int64(1)

In [52]:
arr.max()

np.int64(9)

In [53]:
arr.sum()

np.int64(45)

In [54]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [55]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [56]:
arr.mean()

np.float64(5.0)

In [57]:
arr.std()

np.float64(2.581988897471611)

In [58]:
arr.argmax()

np.int64(8)

In [59]:
arr.argmin()

np.int64(0)

In [ ]:
# Reshaping and Resizing

In [61]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [63]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [64]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])