In [2]:
# Numpy Indexing and Slicing of Vectors
import numpy as np


In [3]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
arr[6]

np.int64(7)

In [9]:
arr[1:5]

array([2, 3, 4, 5])

In [10]:
arr[:5]

array([1, 2, 3, 4, 5])

In [11]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
arr_slice = arr[3::2]
arr_slice

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
# Numpy Indexing and Slicing of Matrix

In [22]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [23]:
arr[0]

array([1, 2, 3, 4, 5])

In [24]:
arr[5]

array([26, 27, 28, 29, 30])

In [26]:
arr[0,0]

np.int64(1)

In [27]:
arr[0,4]

np.int64(5)

In [28]:
arr[5,4]

np.int64(30)

In [29]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [46]:
arr_slice = arr[3:,3:]
arr_slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [48]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [49]:
# Boolean Indexing

In [50]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [53]:
orgArr = arr
orgArr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [55]:
arr

array([12, 14, 16, 18, 20])

In [56]:
orgArr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])