In [1]:
import numpy as np

In [5]:
# Valid Sudoku

In [6]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [7]:
s.sum()

np.int64(405)

In [10]:
b = np.sum(s, axis = 1)
b == 45
b[b == 45]

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [11]:
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [13]:
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("For rows it is valid")

For rows it is valid


In [15]:
c = np.sum(s, axis = 0)

In [16]:
for i in c:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("For columns it is valid")

For columns it is valid


In [17]:
s[0:3, 0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [18]:
s[0:3, 3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [19]:
s[0:3, 6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [21]:
for i in range(0,9,3): 
    for j in range(0,9,3):
        #print(s[i:i + 3, j: j + 3])
        n = s[i:i + 3, j: j + 3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
# General Questions

In [56]:
# Columns: [Age, Math Marks, Science Marks]

data = np.array([
     [18, 85, 78],     # Student 1
     [19, 92, 88],     # Student 2
     [17, 76, 95],     # Student 3
     [18, 65, 70],     # Student 4
     [20, 90, 85]      # Student 5
])

In [ ]:
# Get the shape of the matrix

In [34]:
data.shape
orgData = data

In [ ]:
# Find the average age of students

In [23]:
np.mean(data[:,0]) # Age column

np.float64(18.4)

In [ ]:
# Extract Math marks of all students

In [24]:
data[:, 1] # Only math column

array([85, 92, 76, 65, 90])

In [25]:
# Find the highest Science mark

In [26]:
np.max(data[:,2]) # Science column

np.int64(95)

In [27]:
# Get details of the student who scored more than 90 in Math

In [28]:
data[data[:,1] > 90]

array([[19, 92, 88]])

In [29]:
# Increase Math marks of all students by 5

In [39]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [40]:
data[:,1] +=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [41]:
# Find how many students are younger than 19

In [43]:
len(data[data[:, 0] < 19])

3

In [ ]:
# Calculate the average marks in each subject (Column-wise mean)

In [45]:
np.mean(data[:, 1:], axis = 0)

array([86.6, 83.2])

In [48]:
# Get data of students whoc scored at least 80 in both subjects

In [49]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [ ]:
# Replace all science marks < 75 with 0

In [60]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [61]:
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])